version: '2'
services:

  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=4b2d125d78424de57be
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/data

  web:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - /mnt/data1/oransns/mastodon/public/assets:/mastodon/public/assets
      - /mnt/data1/oransns/mastodon/public/system:/mastodon/public/system

  streaming:
    restart: always
    build: .
    env_file: .env.production
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - /mnt/data1/oransns/mastodon/public/system:/mastodon/public/system
